---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true  #디폴트 fasle. Elasticsearch 노드가 컨테이너화된 환경에서 실행되는 경우인 경우 true

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme